// <auto-generated />
using BulkSyncTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BulkSyncTest.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BulkSyncTest.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeBaseProperty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Base");
                });

            modelBuilder.Entity("BulkSyncTest.InheritA", b =>
                {
                    b.HasBaseType("BulkSyncTest.Base");

                    b.Property<string>("SomeOtherPropA")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("InheritA");
                });

            modelBuilder.Entity("BulkSyncTest.InheritB", b =>
                {
                    b.HasBaseType("BulkSyncTest.Base");

                    b.Property<string>("SomeOtherPropB")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("InheritB");
                });

            modelBuilder.Entity("BulkSyncTest.InheritEmpty", b =>
                {
                    b.HasBaseType("BulkSyncTest.Base");

                    b.HasDiscriminator().HasValue("InheritEmpty");
                });
#pragma warning restore 612, 618
        }
    }
}
